# Generated by Django 5.2.6 on 2025-10-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COTIFAC', '0004_alter_ordencompra_descuento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencompra',
            name='estado',
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='tipo_documento',
            field=models.CharField(choices=[('COTIZACIÓN', 'Cotización'), ('FACTURA', 'Factura')], default='COTIZACIÓN', max_length=20),
        ),
    ]
