# Generated by Django 5.2.6 on 2025-10-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COTIFAC', '0005_remove_ordencompra_estado_ordencompra_tipo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='tipo_documento',
            field=models.CharField(choices=[('COTIZACIÓN', 'COTIZACIÓN'), ('FACTURA', 'FACTURA')], default='COTIZACIÓN', max_length=20),
        ),
    ]
