# Generated by Django 5.2.6 on 2025-11-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COTIFAC', '0006_alter_ordencompra_tipo_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprador', models.CharField(max_length=100)),
                ('razon_social', models.CharField(blank=True, max_length=150, null=True)),
                ('rut', models.CharField(blank=True, max_length=20, null=True)),
                ('giro', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('comuna', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_emision', models.DateField()),
                ('fecha_envio', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
