# Generated by Django 5.2.6 on 2025-11-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COTIFAC', '0007_factura'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Factura',
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='comuna',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='direccion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='giro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='razon_social',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='rut',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='tipo_documento',
            field=models.CharField(choices=[('COTIZACIÓN', 'Cotización'), ('FACTURA', 'Factura')], default='COTIZACIÓN', max_length=20),
        ),
    ]
