# Generated by Django 5.2.6 on 2025-11-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COTIFAC', '0008_delete_factura_ordencompra_ciudad_ordencompra_comuna_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='monto_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
