# Generated by Django 5.2.6 on 2025-11-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COTIFAC', '0009_alter_ordencompra_monto_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
