# Generated by Django 5.2.6 on 2025-12-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COTIFAC', '0010_item_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='nota_descuento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
