services:
  - type: web
    name: cotifac
    env: python
    plan: free

    buildCommand: >
      pip install -r requirements.txt &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py shell -c "
from django.contrib.auth import get_user_model;
User = get_user_model();
User.objects.filter(username='admin').exists() or User.objects.create_superuser('admin', 'admin@example.com', 'Admin1234')
"

    startCommand: "gunicorn COTIFAC.wsgi:application"

    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: COTIFAC.settings
      - key: PYTHON_VERSION
        value: 3.13.7
      - key: DATABASE_URL
        fromDatabase:
          name: cotifac-db       # 👈 Este nombre debe ser igual al que pusiste al crear la DB en Render
          property: connectionString
